const fs = require('fs');
const path = require('path');

// Run this script during build to generate the names array
function generateNamesFile() {
  const namesDirectory = path.join(process.cwd(), 'src/names/names');
  const outputFile = path.join(process.cwd(), 'src/names/names.tsx');
  
  try {
    // Read all files in the directory
    const fileNames = fs.readdirSync(namesDirectory)
      .filter(fileName => {
        const filePath = path.join(namesDirectory, fileName);
        return fs.statSync(filePath).isFile();
      })
      .map(fileName => path.parse(fileName).name);
    
    // Create the content of the names.tsx file
    const content = `// This file is auto-generated by generate-names.js
// Do not edit manually

const names: string[] = ${JSON.stringify(fileNames, null, 2)};

export default names;
`;
    
    // Write the file
    fs.writeFileSync(outputFile, content);
    console.log(`Names file generated at ${outputFile} with ${fileNames.length} names`);
  } catch (error) {
    console.error('Error generating names file:', error);
    process.exit(1);
  }
}

generateNamesFile();